// CID-10 codes commonly used in Brazilian clinical practice (PT-BR).
export interface Cid10 {
  code: string;
  description: string;
}

export const CID10_DATA: Cid10[] = [
  // ── A: Doenças infecciosas intestinais ───────────────────────────────────
  { code: 'A00', description: 'Cólera' },
  { code: 'A01', description: 'Febres tifóide e paratifóide' },
  { code: 'A02', description: 'Outras infecções por Salmonella' },
  { code: 'A03', description: 'Shiguelose' },
  { code: 'A04', description: 'Outras infecções intestinais bacterianas' },
  { code: 'A05', description: 'Outras intoxicações alimentares bacterianas' },
  { code: 'A06', description: 'Amebíase' },
  { code: 'A08', description: 'Infecções intestinais por vírus e outros organismos especificados' },
  { code: 'A09', description: 'Diarreia e gastroenterite de origem infecciosa presumível' },
  // ── A: Tuberculose ───────────────────────────────────────────────────────
  { code: 'A15', description: 'Tuberculose respiratória, com confirmação bacteriológica ou histológica' },
  { code: 'A16', description: 'Tuberculose respiratória, sem confirmação bacteriológica ou histológica' },
  { code: 'A17', description: 'Tuberculose do sistema nervoso' },
  { code: 'A18', description: 'Tuberculose de outros órgãos' },
  { code: 'A19', description: 'Tuberculose miliar' },
  // ── A: Outras bacterioses ────────────────────────────────────────────────
  { code: 'A22', description: 'Carbúnculo (Antraz)' },
  { code: 'A36', description: 'Difteria' },
  { code: 'A37', description: 'Coqueluche' },
  { code: 'A38', description: 'Escarlatina' },
  { code: 'A39', description: 'Infecção meningocócica' },
  { code: 'A40', description: 'Septicemia estreptocócica' },
  { code: 'A41', description: 'Outras septicemias' },
  { code: 'A46', description: 'Erisipela' },
  { code: 'A49', description: 'Infecção bacteriana de localização não especificada' },
  // ── A: Infecções transmitidas sexualmente ────────────────────────────────
  { code: 'A50', description: 'Sífilis congênita' },
  { code: 'A51', description: 'Sífilis precoce' },
  { code: 'A52', description: 'Sífilis tardia' },
  { code: 'A53', description: 'Outras formas e as não especificadas de sífilis' },
  { code: 'A54', description: 'Infecção gonocócica' },
  { code: 'A56', description: 'Outras doenças sexualmente transmissíveis por clamídias' },
  { code: 'A57', description: 'Cancro mole' },
  { code: 'A59', description: 'Tricomoníase' },
  { code: 'A60', description: 'Infecção anorretal e genital por vírus do herpes (herpes simples)' },
  { code: 'A63', description: 'Outras doenças de transmissão predominantemente sexual' },
  { code: 'A64', description: 'Doença sexualmente transmissível sem outra especificação' },
  // ── A: Micoses ───────────────────────────────────────────────────────────
  { code: 'A69.0', description: 'Ulceração oral necrosante' },
  { code: 'A69.1', description: 'Outras infecções de Vincent' },
  // ── B: Viroses ───────────────────────────────────────────────────────────
  { code: 'B00', description: 'Infecções pelo vírus do herpes simples' },
  { code: 'B01', description: 'Varicela' },
  { code: 'B02', description: 'Herpes zóster' },
  { code: 'B05', description: 'Sarampo' },
  { code: 'B06', description: 'Rubéola' },
  { code: 'B07', description: 'Verrugas virais' },
  { code: 'B08', description: 'Outras infecções virais caracterizadas por lesões de pele e mucosas' },
  { code: 'B15', description: 'Hepatite aguda A' },
  { code: 'B16', description: 'Hepatite aguda B' },
  { code: 'B17', description: 'Outras hepatites virais agudas' },
  { code: 'B18', description: 'Hepatite viral crônica' },
  { code: 'B19', description: 'Hepatite viral sem outra especificação' },
  { code: 'B20', description: 'Doença pelo HIV resultando em doenças infecciosas e parasitárias' },
  { code: 'B23', description: 'Doença pelo HIV resultando em outras afecções' },
  { code: 'B24', description: 'Doença pelo HIV sem outra especificação' },
  { code: 'B26', description: 'Caxumba (parotidite epidêmica)' },
  { code: 'B27', description: 'Mononucleose infecciosa' },
  { code: 'B34', description: 'Infecção viral de localização não especificada' },
  { code: 'B34.9', description: 'Infecção viral não especificada' },
  // ── B: Micoses ───────────────────────────────────────────────────────────
  { code: 'B35', description: 'Dermatofitose (tinha)' },
  { code: 'B36', description: 'Outras micoses superficiais' },
  { code: 'B37', description: 'Candidíase' },
  { code: 'B44', description: 'Aspergilose' },
  // ── B: Parasitoses ───────────────────────────────────────────────────────
  { code: 'B50', description: 'Malária por Plasmodium falciparum' },
  { code: 'B54', description: 'Malária não especificada' },
  { code: 'B57', description: 'Doença de Chagas' },
  { code: 'B65', description: 'Esquistossomose' },
  { code: 'B76', description: 'Ancilostomíase' },
  { code: 'B77', description: 'Ascaridíase' },
  { code: 'B79', description: 'Tricuríase' },
  { code: 'B80', description: 'Enterobíase (oxiuríase)' },
  { code: 'B82', description: 'Parasitoses intestinais não especificadas' },
  { code: 'B85', description: 'Pediculose e fitiríase' },
  { code: 'B86', description: 'Escabiose (sarna)' },
  // ── C: Neoplasias malignas ───────────────────────────────────────────────
  { code: 'C00', description: 'Neoplasia maligna do lábio' },
  { code: 'C01', description: 'Neoplasia maligna da base da língua' },
  { code: 'C02', description: 'Neoplasia maligna de outras partes e de partes não especificadas da língua' },
  { code: 'C03', description: 'Neoplasia maligna da gengiva' },
  { code: 'C04', description: 'Neoplasia maligna do assoalho da boca' },
  { code: 'C05', description: 'Neoplasia maligna do palato' },
  { code: 'C06', description: 'Neoplasia maligna de outras partes e de partes não especificadas da boca' },
  { code: 'C07', description: 'Neoplasia maligna da glândula parótida' },
  { code: 'C08', description: 'Neoplasia maligna de outras glândulas salivares maiores e das não especificadas' },
  { code: 'C09', description: 'Neoplasia maligna da amígdala' },
  { code: 'C10', description: 'Neoplasia maligna da orofaringe' },
  { code: 'C11', description: 'Neoplasia maligna da nasofaringe' },
  { code: 'C14', description: 'Neoplasia maligna de outras localizações e de localizações mal definidas do lábio, cavidade oral e faringe' },
  { code: 'C15', description: 'Neoplasia maligna do esôfago' },
  { code: 'C16', description: 'Neoplasia maligna do estômago' },
  { code: 'C18', description: 'Neoplasia maligna do cólon' },
  { code: 'C19', description: 'Neoplasia maligna da junção retossigmóide' },
  { code: 'C20', description: 'Neoplasia maligna do reto' },
  { code: 'C22', description: 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas' },
  { code: 'C25', description: 'Neoplasia maligna do pâncreas' },
  { code: 'C32', description: 'Neoplasia maligna da laringe' },
  { code: 'C33', description: 'Neoplasia maligna da traqueia' },
  { code: 'C34', description: 'Neoplasia maligna dos brônquios e dos pulmões' },
  { code: 'C43', description: 'Melanoma maligno da pele' },
  { code: 'C44', description: 'Outras neoplasias malignas da pele' },
  { code: 'C50', description: 'Neoplasia maligna da mama' },
  { code: 'C53', description: 'Neoplasia maligna do colo do útero' },
  { code: 'C54', description: 'Neoplasia maligna do corpo do útero' },
  { code: 'C56', description: 'Neoplasia maligna do ovário' },
  { code: 'C61', description: 'Neoplasia maligna da próstata' },
  { code: 'C64', description: 'Neoplasia maligna do rim exceto pelve renal' },
  { code: 'C67', description: 'Neoplasia maligna da bexiga' },
  { code: 'C71', description: 'Neoplasia maligna do encéfalo' },
  { code: 'C73', description: 'Neoplasia maligna da glândula tireoide' },
  { code: 'C81', description: 'Doença de Hodgkin' },
  { code: 'C82', description: 'Linfoma não Hodgkin folicular' },
  { code: 'C83', description: 'Linfoma não Hodgkin difuso' },
  { code: 'C90', description: 'Mieloma múltiplo e neoplasias malignas de plasmócitos' },
  { code: 'C91', description: 'Leucemia linfóide' },
  { code: 'C92', description: 'Leucemia mielóide' },
  // ── D: Neoplasias benignas e in situ ────────────────────────────────────
  { code: 'D00', description: 'Carcinoma in situ da cavidade oral, esôfago e estômago' },
  { code: 'D10', description: 'Neoplasia benigna da boca e da faringe' },
  { code: 'D11', description: 'Neoplasia benigna das glândulas salivares maiores' },
  { code: 'D16', description: 'Neoplasia benigna do osso e da cartilagem articular' },
  { code: 'D17', description: 'Neoplasia benigna lipomatosa' },
  { code: 'D21', description: 'Outras neoplasias benignas dos tecidos conjuntivo e outros tecidos moles' },
  { code: 'D25', description: 'Leiomioma do útero' },
  { code: 'D26', description: 'Outras neoplasias benignas do útero' },
  { code: 'D50', description: 'Anemias por deficiência de ferro' },
  { code: 'D51', description: 'Anemia por deficiência de vitamina B12' },
  { code: 'D52', description: 'Anemia por deficiência de folato' },
  { code: 'D53', description: 'Outras anemias nutricionais' },
  { code: 'D64', description: 'Outras anemias' },
  { code: 'D69', description: 'Púrpura e outras afecções hemorrágicas' },
  // ── E: Endócrino / Metabólico ────────────────────────────────────────────
  { code: 'E00', description: 'Síndrome da deficiência congênita de iodo' },
  { code: 'E01', description: 'Transtornos tireoidianos relacionados a deficiência de iodo' },
  { code: 'E02', description: 'Hipotireoidismo subclínico por deficiência de iodo' },
  { code: 'E03', description: 'Outros hipotireoidismos' },
  { code: 'E03.9', description: 'Hipotireoidismo não especificado' },
  { code: 'E04', description: 'Outros bócios não tóxicos' },
  { code: 'E05', description: 'Tireotoxicose (hipertireoidismo)' },
  { code: 'E06', description: 'Tireoidite' },
  { code: 'E06.3', description: 'Tireoidite autoimune (Hashimoto)' },
  { code: 'E07', description: 'Outros transtornos da glândula tireoide' },
  { code: 'E10', description: 'Diabetes mellitus tipo 1' },
  { code: 'E11', description: 'Diabetes mellitus tipo 2' },
  { code: 'E11.0', description: 'Diabetes mellitus tipo 2 com coma' },
  { code: 'E11.2', description: 'Diabetes mellitus tipo 2 com complicações renais' },
  { code: 'E11.3', description: 'Diabetes mellitus tipo 2 com complicações oftálmicas' },
  { code: 'E11.4', description: 'Diabetes mellitus tipo 2 com complicações neurológicas' },
  { code: 'E11.5', description: 'Diabetes mellitus tipo 2 com complicações circulatórias periféricas' },
  { code: 'E11.9', description: 'Diabetes mellitus tipo 2 sem complicações' },
  { code: 'E13', description: 'Outros tipos especificados de diabetes mellitus' },
  { code: 'E14', description: 'Diabetes mellitus não especificado' },
  { code: 'E20', description: 'Hipoparatireoidismo' },
  { code: 'E21', description: 'Hiperparatireoidismo e outros transtornos da glândula paratireoide' },
  { code: 'E22', description: 'Hiperfunção da hipófise' },
  { code: 'E23', description: 'Hipofunção e outros transtornos da hipófise' },
  { code: 'E27', description: 'Outros transtornos da glândula suprarrenal' },
  { code: 'E27.1', description: 'Insuficiência adrenocortical primária (doença de Addison)' },
  { code: 'E28', description: 'Disfunção ovariana' },
  { code: 'E29', description: 'Disfunção testicular' },
  { code: 'E34', description: 'Outros transtornos endócrinos' },
  { code: 'E40', description: 'Kwashiorkor' },
  { code: 'E41', description: 'Marasmo nutricional' },
  { code: 'E43', description: 'Desnutrição proteico-calórica grave não especificada' },
  { code: 'E44', description: 'Desnutrição proteico-calórica de grau moderado e leve' },
  { code: 'E50', description: 'Deficiência de vitamina A' },
  { code: 'E55', description: 'Deficiência de vitamina D (raquitismo)' },
  { code: 'E58', description: 'Deficiência alimentar de cálcio' },
  { code: 'E61', description: 'Deficiência de outros elementos nutritivos' },
  { code: 'E63', description: 'Outras deficiências nutricionais' },
  { code: 'E65', description: 'Adiposidade localizada' },
  { code: 'E66', description: 'Obesidade' },
  { code: 'E66.0', description: 'Obesidade por excesso de calorias' },
  { code: 'E66.1', description: 'Obesidade induzida por drogas' },
  { code: 'E66.9', description: 'Obesidade não especificada' },
  { code: 'E78', description: 'Distúrbios do metabolismo das lipoproteínas e outras lipidemias' },
  { code: 'E78.0', description: 'Hipercolesterolemia pura' },
  { code: 'E78.1', description: 'Hipertrigliceridemia pura' },
  { code: 'E78.2', description: 'Hiperlipidemia mista' },
  { code: 'E78.5', description: 'Hiperlipidemia não especificada' },
  { code: 'E79', description: 'Distúrbios do metabolismo das purinas e pirimidinas' },
  { code: 'E79.0', description: 'Hiperuricemia sem sinais de artrite gotosa' },
  { code: 'E83', description: 'Distúrbios do metabolismo dos minerais' },
  { code: 'E86', description: 'Depleção do volume' },
  { code: 'E87', description: 'Outros transtornos do equilíbrio hidroeletrolítico e ácido-básico' },
  // ── F: Transtornos mentais ───────────────────────────────────────────────
  { code: 'F00', description: 'Demência na doença de Alzheimer' },
  { code: 'F01', description: 'Demência vascular' },
  { code: 'F02', description: 'Demência em outras doenças classificadas em outra parte' },
  { code: 'F03', description: 'Demência não especificada' },
  { code: 'F05', description: 'Delirium não sobreposto à demência, assim descrito' },
  { code: 'F10', description: 'Transtornos mentais e comportamentais devidos ao uso de álcool' },
  { code: 'F10.2', description: 'Síndrome de dependência do álcool' },
  { code: 'F11', description: 'Transtornos mentais e comportamentais devidos ao uso de opioides' },
  { code: 'F12', description: 'Transtornos mentais devidos ao uso de canabinoides' },
  { code: 'F14', description: 'Transtornos mentais devidos ao uso da cocaína' },
  { code: 'F17', description: 'Transtornos mentais devidos ao uso de fumo (tabaco)' },
  { code: 'F19', description: 'Transtornos mentais devidos ao uso de múltiplas drogas' },
  { code: 'F20', description: 'Esquizofrenia' },
  { code: 'F21', description: 'Transtorno esquizotípico' },
  { code: 'F22', description: 'Transtornos delirantes persistentes' },
  { code: 'F25', description: 'Transtornos esquizoafetivos' },
  { code: 'F29', description: 'Psicose não orgânica não especificada' },
  { code: 'F30', description: 'Episódio maníaco' },
  { code: 'F31', description: 'Transtorno afetivo bipolar' },
  { code: 'F32', description: 'Episódios depressivos' },
  { code: 'F32.0', description: 'Episódio depressivo leve' },
  { code: 'F32.1', description: 'Episódio depressivo moderado' },
  { code: 'F32.2', description: 'Episódio depressivo grave sem sintomas psicóticos' },
  { code: 'F32.3', description: 'Episódio depressivo grave com sintomas psicóticos' },
  { code: 'F33', description: 'Transtorno depressivo recorrente' },
  { code: 'F40', description: 'Transtornos fóbico-ansiosos' },
  { code: 'F40.1', description: 'Fobias sociais' },
  { code: 'F41', description: 'Outros transtornos ansiosos' },
  { code: 'F41.0', description: 'Transtorno de pânico (ansiedade paroxística episódica)' },
  { code: 'F41.1', description: 'Ansiedade generalizada' },
  { code: 'F41.2', description: 'Transtorno misto ansioso e depressivo' },
  { code: 'F42', description: 'Transtorno obsessivo-compulsivo (TOC)' },
  { code: 'F43', description: 'Reações ao estresse grave e transtornos de adaptação' },
  { code: 'F43.1', description: 'Estado de estresse pós-traumático (PTSD)' },
  { code: 'F43.2', description: 'Transtornos de adaptação' },
  { code: 'F44', description: 'Transtornos dissociativos (de conversão)' },
  { code: 'F45', description: 'Transtornos somatoformes' },
  { code: 'F48', description: 'Outros transtornos neuróticos' },
  { code: 'F50', description: 'Transtornos alimentares' },
  { code: 'F50.0', description: 'Anorexia nervosa' },
  { code: 'F50.2', description: 'Bulimia nervosa' },
  { code: 'F51', description: 'Transtornos do sono não orgânicos' },
  { code: 'F51.0', description: 'Insônia não orgânica' },
  { code: 'F60', description: 'Transtornos específicos da personalidade' },
  { code: 'F64', description: 'Transtornos de identidade de gênero' },
  { code: 'F70', description: 'Retardo mental leve' },
  { code: 'F71', description: 'Retardo mental moderado' },
  { code: 'F80', description: 'Transtornos específicos do desenvolvimento da fala e da linguagem' },
  { code: 'F84', description: 'Transtornos globais do desenvolvimento' },
  { code: 'F84.0', description: 'Autismo infantil' },
  { code: 'F84.5', description: 'Síndrome de Asperger' },
  { code: 'F90', description: 'Transtornos hipercinéticos (TDAH)' },
  { code: 'F90.0', description: 'Distúrbio de atividade e atenção (TDAH - apresentação predominante desatenta)' },
  { code: 'F91', description: 'Transtornos de conduta' },
  { code: 'F93', description: 'Transtornos emocionais com início especificamente na infância' },
  { code: 'F95', description: 'Transtornos por tiques' },
  { code: 'F95.2', description: 'Síndrome de Gilles de la Tourette' },
  // ── G: Sistema nervoso ───────────────────────────────────────────────────
  { code: 'G00', description: 'Meningite bacteriana' },
  { code: 'G03', description: 'Meningite devida a outras causas e a causas não especificadas' },
  { code: 'G04', description: 'Encefalite, mielite e encefalomielite' },
  { code: 'G06', description: 'Abscesso e granuloma intracranianos e intraespinhais' },
  { code: 'G10', description: 'Doença de Huntington' },
  { code: 'G11', description: 'Ataxias hereditárias' },
  { code: 'G12', description: 'Atrofia muscular espinhal e síndromes correlatas' },
  { code: 'G20', description: 'Doença de Parkinson' },
  { code: 'G21', description: 'Parkinsonismo secundário' },
  { code: 'G25', description: 'Outros transtornos extrapiramidais e do movimento' },
  { code: 'G30', description: 'Doença de Alzheimer' },
  { code: 'G35', description: 'Esclerose múltipla' },
  { code: 'G40', description: 'Epilepsia' },
  { code: 'G40.0', description: 'Epilepsia e síndromes epilépticas idiopáticas relacionadas à localização' },
  { code: 'G40.3', description: 'Epilepsia generalizada idiopática' },
  { code: 'G40.9', description: 'Epilepsia sem outra especificação' },
  { code: 'G41', description: 'Estado de mal epiléptico' },
  { code: 'G43', description: 'Enxaqueca (migrânea)' },
  { code: 'G43.0', description: 'Enxaqueca sem aura (enxaqueca comum)' },
  { code: 'G43.1', description: 'Enxaqueca com aura (enxaqueca clássica)' },
  { code: 'G44', description: 'Outras síndromes de algias cefálicas' },
  { code: 'G44.2', description: 'Cefaleia tensional' },
  { code: 'G45', description: 'Ataques isquêmicos transitórios e síndromes correlatas' },
  { code: 'G47', description: 'Transtornos do sono' },
  { code: 'G47.0', description: 'Distúrbios do início e da manutenção do sono (insônia)' },
  { code: 'G47.3', description: 'Apneia do sono' },
  { code: 'G50', description: 'Transtornos do nervo trigêmeo' },
  { code: 'G50.0', description: 'Nevralgia do trigêmeo' },
  { code: 'G51', description: 'Transtornos do nervo facial' },
  { code: 'G51.0', description: 'Paralisia de Bell (paralisia facial)' },
  { code: 'G54', description: 'Transtornos das raízes e dos plexos nervosos' },
  { code: 'G54.2', description: 'Comprometimento das raízes cervicais' },
  { code: 'G54.4', description: 'Comprometimento das raízes lombossacrais' },
  { code: 'G56', description: 'Mononeuropatias dos membros superiores' },
  { code: 'G56.0', description: 'Síndrome do túnel do carpo' },
  { code: 'G57', description: 'Mononeuropatias dos membros inferiores' },
  { code: 'G60', description: 'Neuropatia hereditária e idiopática' },
  { code: 'G61', description: 'Polineuropatia inflamatória' },
  { code: 'G62', description: 'Outras polineuropatias' },
  { code: 'G70', description: 'Miastenia gravis e outros transtornos neuromusculares' },
  { code: 'G71', description: 'Transtornos musculares primários' },
  { code: 'G80', description: 'Paralisia cerebral' },
  { code: 'G89', description: 'Síndromes dolorosas não classificadas em outra parte' },
  { code: 'G91', description: 'Hidrocefalia' },
  { code: 'G93', description: 'Outros transtornos encefálicos' },
  { code: 'G95', description: 'Outras doenças da medula espinhal' },
  // ── H: Olho ──────────────────────────────────────────────────────────────
  { code: 'H00', description: 'Hordéolo e calázio' },
  { code: 'H01', description: 'Outras inflamações da pálpebra' },
  { code: 'H02', description: 'Outros transtornos da pálpebra' },
  { code: 'H04', description: 'Transtornos do aparelho lacrimal' },
  { code: 'H10', description: 'Conjuntivite' },
  { code: 'H10.0', description: 'Conjuntivite mucopurulenta' },
  { code: 'H10.1', description: 'Conjuntivite atópica aguda' },
  { code: 'H11', description: 'Outros transtornos da conjuntiva' },
  { code: 'H15', description: 'Transtornos da esclerótica' },
  { code: 'H16', description: 'Ceratite' },
  { code: 'H18', description: 'Outros transtornos da córnea' },
  { code: 'H20', description: 'Iridociclite' },
  { code: 'H25', description: 'Catarata senil' },
  { code: 'H26', description: 'Outras cataratas' },
  { code: 'H33', description: 'Descolamento e defeitos da retina' },
  { code: 'H35', description: 'Outros transtornos da retina' },
  { code: 'H36', description: 'Transtornos da retina em doenças classificadas em outra parte' },
  { code: 'H40', description: 'Glaucoma' },
  { code: 'H43', description: 'Transtornos do humor vítreo' },
  { code: 'H52', description: 'Transtornos da refração e da acomodação' },
  { code: 'H52.0', description: 'Hipermetropia' },
  { code: 'H52.1', description: 'Miopia' },
  { code: 'H52.2', description: 'Astigmatismo' },
  { code: 'H52.4', description: 'Presbiopia' },
  { code: 'H53', description: 'Distúrbios visuais' },
  { code: 'H54', description: 'Cegueira e visão subnormal' },
  // ── H: Ouvido ────────────────────────────────────────────────────────────
  { code: 'H60', description: 'Otite externa' },
  { code: 'H65', description: 'Otite média não supurativa' },
  { code: 'H66', description: 'Otite média supurativa e a não especificada' },
  { code: 'H70', description: 'Mastoidite e afecções correlatas' },
  { code: 'H72', description: 'Perfuração da membrana timpânica' },
  { code: 'H81', description: 'Transtornos da função vestibular' },
  { code: 'H81.0', description: 'Doença de Ménière' },
  { code: 'H81.1', description: 'Vertigem posicional paroxística benigna' },
  { code: 'H83', description: 'Outros transtornos do ouvido interno' },
  { code: 'H90', description: 'Perda de audição por transtorno de condução e neuro-sensorial' },
  { code: 'H91', description: 'Outras perdas de audição' },
  { code: 'H92', description: 'Otalgia e secreção auditiva' },
  // ── I: Sistema circulatório ──────────────────────────────────────────────
  { code: 'I00', description: 'Febre reumática sem menção de comprometimento do coração' },
  { code: 'I05', description: 'Doenças reumáticas da valva mitral' },
  { code: 'I08', description: 'Transtornos de múltiplas valvas' },
  { code: 'I10', description: 'Hipertensão essencial (primária)' },
  { code: 'I11', description: 'Doença cardíaca hipertensiva' },
  { code: 'I12', description: 'Doença renal hipertensiva' },
  { code: 'I13', description: 'Doença cardíaca e renal hipertensiva' },
  { code: 'I20', description: 'Angina pectoris' },
  { code: 'I20.0', description: 'Angina instável' },
  { code: 'I20.9', description: 'Angina pectoris não especificada' },
  { code: 'I21', description: 'Infarto agudo do miocárdio' },
  { code: 'I21.0', description: 'Infarto agudo do miocárdio da parede anterior' },
  { code: 'I21.1', description: 'Infarto agudo do miocárdio da parede inferior' },
  { code: 'I22', description: 'Infarto do miocárdio recorrente' },
  { code: 'I25', description: 'Doença isquêmica crônica do coração' },
  { code: 'I26', description: 'Embolia pulmonar' },
  { code: 'I27', description: 'Outras formas de doença cardíaca pulmonar' },
  { code: 'I30', description: 'Pericardite aguda' },
  { code: 'I34', description: 'Transtornos não reumáticos da valva mitral' },
  { code: 'I35', description: 'Transtornos não reumáticos da valva aórtica' },
  { code: 'I40', description: 'Miocardite aguda' },
  { code: 'I42', description: 'Cardiomiopatias' },
  { code: 'I44', description: 'Bloqueio atrioventricular e do ramo esquerdo' },
  { code: 'I45', description: 'Outros transtornos da condução' },
  { code: 'I47', description: 'Taquicardia paroxística' },
  { code: 'I48', description: 'Fibrilação e flutter atrial' },
  { code: 'I49', description: 'Outras arritmias cardíacas' },
  { code: 'I50', description: 'Insuficiência cardíaca' },
  { code: 'I50.0', description: 'Insuficiência cardíaca congestiva' },
  { code: 'I51', description: 'Complicações e síndromes cardíacas mal definidas' },
  { code: 'I60', description: 'Hemorragia subaracnóidea' },
  { code: 'I61', description: 'Hemorragia intracerebral' },
  { code: 'I63', description: 'Infarto cerebral (AVC isquêmico)' },
  { code: 'I64', description: 'Acidente vascular cerebral não especificado como hemorrágico ou isquêmico' },
  { code: 'I65', description: 'Oclusão e estenose de artérias pré-cerebrais' },
  { code: 'I70', description: 'Aterosclerose' },
  { code: 'I73', description: 'Outras doenças vasculares periféricas' },
  { code: 'I74', description: 'Embolia e trombose arteriais' },
  { code: 'I80', description: 'Flebite e tromboflebite' },
  { code: 'I83', description: 'Varizes dos membros inferiores' },
  { code: 'I84', description: 'Hemorroidas' },
  { code: 'I87', description: 'Outros transtornos das veias' },
  { code: 'I89', description: 'Outros transtornos não infecciosos dos vasos linfáticos e dos gânglios linfáticos' },
  // ── J: Sistema respiratório ──────────────────────────────────────────────
  { code: 'J00', description: 'Nasofaringite aguda (resfriado comum)' },
  { code: 'J01', description: 'Sinusite aguda' },
  { code: 'J02', description: 'Faringite aguda' },
  { code: 'J02.9', description: 'Faringite aguda não especificada' },
  { code: 'J03', description: 'Amigdalite aguda' },
  { code: 'J03.9', description: 'Amigdalite aguda não especificada' },
  { code: 'J04', description: 'Laringite e traqueíte agudas' },
  { code: 'J05', description: 'Laringite obstrutiva aguda (crupe) e epiglotite' },
  { code: 'J06', description: 'Infecções agudas das vias aéreas superiores' },
  { code: 'J06.9', description: 'Infecção aguda das vias aéreas superiores não especificada' },
  { code: 'J10', description: 'Influenza (gripe) devida a vírus influenza identificado' },
  { code: 'J11', description: 'Influenza (gripe) devida a vírus não identificado' },
  { code: 'J12', description: 'Pneumonia viral não classificada em outra parte' },
  { code: 'J13', description: 'Pneumonia devida a Streptococcus pneumoniae' },
  { code: 'J14', description: 'Pneumonia devida a Haemophilus influenzae' },
  { code: 'J15', description: 'Pneumonia bacteriana não classificada em outra parte' },
  { code: 'J18', description: 'Pneumonia por microrganismo não especificado' },
  { code: 'J20', description: 'Bronquite aguda' },
  { code: 'J21', description: 'Bronquiolite aguda' },
  { code: 'J30', description: 'Rinite alérgica e vasomotora' },
  { code: 'J30.0', description: 'Rinite vasomotora' },
  { code: 'J30.1', description: 'Rinite alérgica devida a pólen' },
  { code: 'J30.4', description: 'Rinite alérgica não especificada' },
  { code: 'J31', description: 'Rinite, nasofaringite e faringite crônicas' },
  { code: 'J32', description: 'Sinusite crônica' },
  { code: 'J35', description: 'Doenças crônicas das amígdalas e das vegetações adenóides' },
  { code: 'J36', description: 'Abscesso periamigdaliano' },
  { code: 'J37', description: 'Laringite e laringotraqueíte crônicas' },
  { code: 'J38', description: 'Doenças das pregas vocais e da laringe não classificadas em outra parte' },
  { code: 'J40', description: 'Bronquite não especificada como aguda ou crônica' },
  { code: 'J41', description: 'Bronquite crônica simples e a mucopurulenta' },
  { code: 'J42', description: 'Bronquite crônica não especificada' },
  { code: 'J43', description: 'Enfisema' },
  { code: 'J44', description: 'Outras doenças pulmonares obstrutivas crônicas (DPOC)' },
  { code: 'J45', description: 'Asma' },
  { code: 'J45.0', description: 'Asma predominantemente alérgica' },
  { code: 'J45.1', description: 'Asma não alérgica' },
  { code: 'J45.9', description: 'Asma não especificada' },
  { code: 'J46', description: 'Estado de mal asmático' },
  { code: 'J47', description: 'Bronquiectasia' },
  { code: 'J60', description: 'Pneumoconiose dos mineradores de carvão' },
  { code: 'J68', description: 'Afecções respiratórias devidas à inalação de produtos químicos' },
  { code: 'J69', description: 'Pneumonite devida a sólidos e líquidos' },
  { code: 'J80', description: 'Síndrome do desconforto respiratório do adulto (SDRA)' },
  { code: 'J84', description: 'Outras doenças pulmonares intersticiais' },
  { code: 'J90', description: 'Derrame pleural' },
  { code: 'J93', description: 'Pneumotórax' },
  { code: 'J96', description: 'Insuficiência respiratória não classificada em outra parte' },
  // ── K: Sistema digestivo ─────────────────────────────────────────────────
  { code: 'K00', description: 'Transtornos do desenvolvimento e da erupção dos dentes' },
  { code: 'K01', description: 'Dentes inclusos e impactados' },
  { code: 'K02', description: 'Cárie dentária' },
  { code: 'K03', description: 'Outras doenças dos tecidos duros dos dentes' },
  { code: 'K04', description: 'Doenças da polpa e dos tecidos periapicais' },
  { code: 'K04.0', description: 'Pulpite' },
  { code: 'K04.1', description: 'Necrose da polpa' },
  { code: 'K04.5', description: 'Periodontite apical crônica' },
  { code: 'K04.6', description: 'Abscesso periapical com fístula' },
  { code: 'K04.7', description: 'Abscesso periapical sem fístula' },
  { code: 'K05', description: 'Gengivite e doenças periodontais' },
  { code: 'K05.0', description: 'Gengivite aguda' },
  { code: 'K05.1', description: 'Gengivite crônica' },
  { code: 'K05.2', description: 'Periodontite aguda' },
  { code: 'K05.3', description: 'Periodontite crônica' },
  { code: 'K06', description: 'Outros transtornos da gengiva e do rebordo alveolar' },
  { code: 'K07', description: 'Anomalias dentofaciais (inclusive má oclusão)' },
  { code: 'K08', description: 'Outros transtornos dos dentes e das estruturas de sustentação' },
  { code: 'K09', description: 'Cistos da região bucal não classificados em outra parte' },
  { code: 'K10', description: 'Outras doenças dos maxilares' },
  { code: 'K11', description: 'Doenças das glândulas salivares' },
  { code: 'K12', description: 'Estomatite e lesões correlatas' },
  { code: 'K12.0', description: 'Aftas bucais recorrentes' },
  { code: 'K13', description: 'Outras doenças dos lábios e da mucosa oral' },
  { code: 'K14', description: 'Doenças da língua' },
  { code: 'K20', description: 'Esofagite' },
  { code: 'K21', description: 'Doença do refluxo gastroesofágico' },
  { code: 'K21.0', description: 'Doença do refluxo gastroesofágico com esofagite' },
  { code: 'K21.9', description: 'Doença do refluxo gastroesofágico sem esofagite' },
  { code: 'K22', description: 'Outras doenças do esôfago' },
  { code: 'K25', description: 'Úlcera gástrica' },
  { code: 'K26', description: 'Úlcera duodenal' },
  { code: 'K29', description: 'Gastrite e duodenite' },
  { code: 'K30', description: 'Dispepsia' },
  { code: 'K35', description: 'Apendicite aguda' },
  { code: 'K37', description: 'Apendicite sem outra especificação' },
  { code: 'K40', description: 'Hérnia inguinal' },
  { code: 'K41', description: 'Hérnia femoral' },
  { code: 'K43', description: 'Hérnia ventral' },
  { code: 'K44', description: 'Hérnia diafragmática' },
  { code: 'K50', description: 'Doença de Crohn (enterite regional)' },
  { code: 'K51', description: 'Retocolite ulcerativa inespecífica' },
  { code: 'K52', description: 'Outras gastroenterites e colites não infecciosas' },
  { code: 'K57', description: 'Doença diverticular do intestino' },
  { code: 'K58', description: 'Síndrome do intestino irritável (SII)' },
  { code: 'K59', description: 'Outros transtornos funcionais do intestino' },
  { code: 'K59.0', description: 'Constipação (obstipação intestinal)' },
  { code: 'K59.1', description: 'Diarreia funcional' },
  { code: 'K60', description: 'Fissura e fístula da região anal e retal' },
  { code: 'K61', description: 'Abscesso da região anal e retal' },
  { code: 'K62', description: 'Outras doenças do reto e do ânus' },
  { code: 'K70', description: 'Doença alcoólica do fígado' },
  { code: 'K72', description: 'Insuficiência hepática' },
  { code: 'K73', description: 'Hepatite crônica não classificada em outra parte' },
  { code: 'K74', description: 'Fibrose e cirrose hepáticas' },
  { code: 'K76', description: 'Outras doenças do fígado' },
  { code: 'K76.0', description: 'Esteatose hepática (fígado gorduroso)' },
  { code: 'K80', description: 'Colelitíase (cálculo biliar)' },
  { code: 'K81', description: 'Colecistite' },
  { code: 'K85', description: 'Pancreatite aguda' },
  { code: 'K86', description: 'Outras doenças do pâncreas' },
  { code: 'K86.1', description: 'Outras pancreatites crônicas' },
  // ── L: Pele e tecido subcutâneo ──────────────────────────────────────────
  { code: 'L00', description: 'Síndrome estafilocócica da pele escaldada' },
  { code: 'L01', description: 'Impetigo' },
  { code: 'L02', description: 'Abscesso cutâneo, furúnculo e carbúnculo' },
  { code: 'L03', description: 'Celulite' },
  { code: 'L04', description: 'Linfadenite aguda' },
  { code: 'L08', description: 'Outras infecções locais da pele e do tecido subcutâneo' },
  { code: 'L10', description: 'Pênfigo' },
  { code: 'L20', description: 'Dermatite atópica' },
  { code: 'L22', description: 'Dermatite das fraldas' },
  { code: 'L23', description: 'Dermatite alérgica de contato' },
  { code: 'L24', description: 'Dermatite de contato por irritante' },
  { code: 'L25', description: 'Dermatite de contato não especificada' },
  { code: 'L27', description: 'Dermatite devida a substâncias ingeridas' },
  { code: 'L28', description: 'Líquen simples crônico e prurigo' },
  { code: 'L29', description: 'Prurido' },
  { code: 'L30', description: 'Outras dermatites' },
  { code: 'L40', description: 'Psoríase' },
  { code: 'L41', description: 'Parapsoriase' },
  { code: 'L42', description: 'Pitiríase rósea' },
  { code: 'L43', description: 'Líquen plano' },
  { code: 'L50', description: 'Urticária' },
  { code: 'L51', description: 'Eritema multiforme' },
  { code: 'L53', description: 'Outras afecções eritematosas' },
  { code: 'L57', description: 'Alterações cutâneas devidas à exposição crônica à radiação não ionizante' },
  { code: 'L60', description: 'Transtornos das unhas' },
  { code: 'L63', description: 'Alopecia areata' },
  { code: 'L64', description: 'Alopecia androgenética' },
  { code: 'L65', description: 'Outras formas de perda de cabelos' },
  { code: 'L70', description: 'Acne' },
  { code: 'L70.0', description: 'Acne vulgar' },
  { code: 'L71', description: 'Rosácea' },
  { code: 'L72', description: 'Cistos foliculares da pele e do tecido subcutâneo' },
  { code: 'L73', description: 'Outros transtornos foliculares' },
  { code: 'L80', description: 'Vitiligo' },
  { code: 'L82', description: 'Ceratose seborreica' },
  { code: 'L84', description: 'Calos e calosidades' },
  { code: 'L89', description: 'Úlcera de decúbito' },
  { code: 'L90', description: 'Afecções atróficas da pele' },
  { code: 'L91', description: 'Afecções hipertróficas da pele' },
  { code: 'L92', description: 'Afecções granulomatosas da pele e do tecido subcutâneo' },
  { code: 'L93', description: 'Lúpus eritematoso cutâneo' },
  { code: 'L98', description: 'Outras afecções da pele e do tecido subcutâneo' },
  // ── M: Sistema musculoesquelético ────────────────────────────────────────
  { code: 'M00', description: 'Artrite piogênica' },
  { code: 'M05', description: 'Artrite reumatoide soropositiva' },
  { code: 'M06', description: 'Outras artrites reumatoides' },
  { code: 'M08', description: 'Artrite juvenil' },
  { code: 'M10', description: 'Gota' },
  { code: 'M13', description: 'Outras artrites' },
  { code: 'M15', description: 'Poliartrose' },
  { code: 'M16', description: 'Coxartrose (artrose do quadril)' },
  { code: 'M17', description: 'Gonartrose (artrose do joelho)' },
  { code: 'M19', description: 'Outras artroses' },
  { code: 'M20', description: 'Deformidades adquiridas dos dedos das mãos e dos pés' },
  { code: 'M23', description: 'Transtornos internos dos joelhos' },
  { code: 'M24', description: 'Outros transtornos articulares específicos' },
  { code: 'M25', description: 'Outros transtornos articulares não classificados em outra parte' },
  { code: 'M25.5', description: 'Dor articular' },
  { code: 'M32', description: 'Lúpus eritematoso sistêmico (LES)' },
  { code: 'M33', description: 'Dermatopolimiosite' },
  { code: 'M34', description: 'Esclerose sistêmica' },
  { code: 'M35', description: 'Outras afecções sistêmicas do tecido conjuntivo' },
  { code: 'M35.0', description: 'Síndrome de Sjögren' },
  { code: 'M40', description: 'Cifose e lordose' },
  { code: 'M41', description: 'Escoliose' },
  { code: 'M43', description: 'Outras dorsopatias deformantes' },
  { code: 'M47', description: 'Espondilose' },
  { code: 'M48', description: 'Outras espondilopatias' },
  { code: 'M50', description: 'Transtornos dos discos cervicais' },
  { code: 'M51', description: 'Outros transtornos dos discos intervertebrais' },
  { code: 'M51.1', description: 'Degeneração dos discos lombares e de outros discos intervertebrais com radiculopatia' },
  { code: 'M54', description: 'Dorsalgia' },
  { code: 'M54.2', description: 'Cervicalgia' },
  { code: 'M54.3', description: 'Ciática' },
  { code: 'M54.4', description: 'Lumbago com ciática' },
  { code: 'M54.5', description: 'Lombalgia' },
  { code: 'M60', description: 'Miosite' },
  { code: 'M65', description: 'Sinovite e tenossinovite' },
  { code: 'M70', description: 'Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão' },
  { code: 'M75', description: 'Lesões do ombro' },
  { code: 'M75.0', description: 'Capsulite adesiva do ombro (ombro congelado)' },
  { code: 'M75.1', description: 'Síndrome do manguito rotador' },
  { code: 'M77', description: 'Outras entesopatias' },
  { code: 'M77.0', description: 'Epicondilite medial (cotovelo de golfista)' },
  { code: 'M77.1', description: 'Epicondilite lateral (cotovelo de tenista)' },
  { code: 'M79', description: 'Outros transtornos dos tecidos moles não classificados em outra parte' },
  { code: 'M79.1', description: 'Mialgia' },
  { code: 'M79.3', description: 'Paniculite' },
  { code: 'M79.7', description: 'Fibromialgia' },
  { code: 'M80', description: 'Osteoporose com fratura patológica' },
  { code: 'M81', description: 'Osteoporose sem fratura patológica' },
  { code: 'M84', description: 'Transtornos da continuidade do osso' },
  { code: 'M85', description: 'Outros transtornos da densidade e da estrutura ósseas' },
  // ── N: Sistema geniturinário ─────────────────────────────────────────────
  { code: 'N00', description: 'Síndrome nefrítica aguda' },
  { code: 'N02', description: 'Hematúria recorrente e persistente' },
  { code: 'N03', description: 'Síndrome nefrítica crônica' },
  { code: 'N04', description: 'Síndrome nefrótica' },
  { code: 'N10', description: 'Nefrite túbulo-intersticial aguda (pielonefrite aguda)' },
  { code: 'N11', description: 'Nefrite túbulo-intersticial crônica' },
  { code: 'N13', description: 'Uropatia obstrutiva e por refluxo' },
  { code: 'N17', description: 'Insuficiência renal aguda' },
  { code: 'N18', description: 'Doença renal crônica' },
  { code: 'N18.3', description: 'Doença renal crônica estágio 3' },
  { code: 'N18.5', description: 'Doença renal crônica estágio 5' },
  { code: 'N20', description: 'Cálculo do rim e do ureter (nefrolitíase)' },
  { code: 'N21', description: 'Cálculo das vias urinárias inferiores' },
  { code: 'N25', description: 'Transtornos resultantes de função tubular renal alterada' },
  { code: 'N28', description: 'Outros transtornos do rim e do ureter' },
  { code: 'N30', description: 'Cistite' },
  { code: 'N34', description: 'Uretrite e síndrome uretral' },
  { code: 'N35', description: 'Estenose uretral' },
  { code: 'N39', description: 'Outros transtornos do sistema urinário' },
  { code: 'N39.0', description: 'Infecção do trato urinário de localização não especificada' },
  { code: 'N39.3', description: 'Incontinência de estresse' },
  { code: 'N40', description: 'Hiperplasia da próstata (HPB)' },
  { code: 'N41', description: 'Doenças inflamatórias da próstata' },
  { code: 'N41.0', description: 'Prostatite aguda' },
  { code: 'N41.1', description: 'Prostatite crônica' },
  { code: 'N42', description: 'Outras afecções da próstata' },
  { code: 'N43', description: 'Hidrocele e espermatocele' },
  { code: 'N45', description: 'Orquite e epididimite' },
  { code: 'N46', description: 'Infertilidade masculina' },
  { code: 'N48', description: 'Outros transtornos do pênis' },
  { code: 'N50', description: 'Outros transtornos dos órgãos genitais masculinos' },
  { code: 'N60', description: 'Displasia mamária benigna' },
  { code: 'N61', description: 'Doenças inflamatórias da mama' },
  { code: 'N63', description: 'Nódulo não especificado na mama' },
  { code: 'N70', description: 'Salpingite e ooforite' },
  { code: 'N71', description: 'Doença inflamatória do útero exceto o colo' },
  { code: 'N72', description: 'Doença inflamatória do colo do útero (cervicite)' },
  { code: 'N73', description: 'Outras doenças inflamatórias pélvicas femininas' },
  { code: 'N75', description: 'Doenças da glândula de Bartholin' },
  { code: 'N76', description: 'Outras afecções inflamatórias da vagina e da vulva (vulvovaginite)' },
  { code: 'N80', description: 'Endometriose' },
  { code: 'N81', description: 'Prolapso genital feminino' },
  { code: 'N83', description: 'Transtornos não inflamatórios do ovário, da tuba uterina e do ligamento largo' },
  { code: 'N83.2', description: 'Outros cistos do ovário' },
  { code: 'N84', description: 'Pólipo do trato genital feminino' },
  { code: 'N85', description: 'Outros transtornos não inflamatórios do útero exceto o colo' },
  { code: 'N87', description: 'Displasia do colo do útero' },
  { code: 'N89', description: 'Outros transtornos não inflamatórios da vagina' },
  { code: 'N90', description: 'Outros transtornos não inflamatórios da vulva e do períneo' },
  { code: 'N91', description: 'Menstruação ausente, escassa e rara (amenorreia)' },
  { code: 'N92', description: 'Menstruação excessiva, frequente e irregular' },
  { code: 'N93', description: 'Outros sangramentos uterinos ou vaginais anormais' },
  { code: 'N94', description: 'Dor e outras afecções associadas aos órgãos genitais femininos' },
  { code: 'N94.3', description: 'Síndrome de tensão pré-menstrual (TPM)' },
  { code: 'N94.6', description: 'Dismenorreia não especificada' },
  { code: 'N95', description: 'Transtornos da menopausa e da perimenopausa' },
  { code: 'N95.1', description: 'Estados da menopausa e climatério feminino' },
  // ── O: Gravidez, parto e puerpério ───────────────────────────────────────
  { code: 'O00', description: 'Gravidez ectópica' },
  { code: 'O02', description: 'Outros produtos anormais da concepção' },
  { code: 'O03', description: 'Aborto espontâneo' },
  { code: 'O10', description: 'Hipertensão pré-existente complicando a gravidez, o parto e o puerpério' },
  { code: 'O11', description: 'Distúrbio hipertensivo pré-existente com pré-eclâmpsia' },
  { code: 'O13', description: 'Hipertensão gestacional (induzida pela gravidez)' },
  { code: 'O14', description: 'Pré-eclâmpsia' },
  { code: 'O15', description: 'Eclâmpsia' },
  { code: 'O20', description: 'Hemorragia no início da gravidez' },
  { code: 'O21', description: 'Vômitos excessivos na gravidez (hiperêmese gravídica)' },
  { code: 'O24', description: 'Diabetes mellitus na gravidez' },
  { code: 'O26', description: 'Assistência prestada à mãe por outras complicações ligadas predominantemente à gravidez' },
  { code: 'O30', description: 'Gestação múltipla' },
  { code: 'O34', description: 'Assistência prestada à mãe por anomalia conhecida ou suspeita dos órgãos pélvicos da mãe' },
  { code: 'O42', description: 'Ruptura prematura de membranas' },
  { code: 'O60', description: 'Trabalho de parto pré-termo' },
  { code: 'O62', description: 'Anormalidades da contração uterina' },
  { code: 'O80', description: 'Parto único espontâneo' },
  { code: 'O82', description: 'Parto por cesariana' },
  { code: 'O85', description: 'Sepse puerperal' },
  { code: 'O86', description: 'Outras infecções puerperais' },
  { code: 'O90', description: 'Complicações do puerpério não classificadas em outra parte' },
  { code: 'O92', description: 'Outros transtornos da mama e da amamentação associados ao parto' },
  // ── P: Perinatal ─────────────────────────────────────────────────────────
  { code: 'P07', description: 'Transtornos relacionados com gestação curta e baixo peso ao nascer' },
  { code: 'P20', description: 'Hipóxia intrauterina' },
  { code: 'P21', description: 'Asfixia ao nascer' },
  { code: 'P22', description: 'Desconforto respiratório do recém-nascido' },
  { code: 'P36', description: 'Septicemia bacteriana do recém-nascido' },
  { code: 'P59', description: 'Icterícia neonatal por outras causas e por causas não especificadas' },
  // ── Q: Malformações congênitas ───────────────────────────────────────────
  { code: 'Q20', description: 'Malformações congênitas das câmaras e das comunicações cardíacas' },
  { code: 'Q21', description: 'Malformações congênitas dos septos cardíacos' },
  { code: 'Q35', description: 'Fissura palatina' },
  { code: 'Q36', description: 'Lábio leporino' },
  { code: 'Q37', description: 'Fissura palatina com lábio leporino' },
  { code: 'Q65', description: 'Malformações congênitas do quadril' },
  { code: 'Q66', description: 'Deformidades congênitas dos pés' },
  { code: 'Q90', description: 'Síndrome de Down (trissomia 21)' },
  { code: 'Q93', description: 'Monossomias e deleções dos autossomos' },
  // ── R: Sintomas e sinais ─────────────────────────────────────────────────
  { code: 'R00', description: 'Anormalidades do batimento cardíaco' },
  { code: 'R00.0', description: 'Taquicardia não especificada' },
  { code: 'R00.1', description: 'Bradicardia não especificada' },
  { code: 'R00.8', description: 'Outras anormalidades do batimento cardíaco e as não especificadas' },
  { code: 'R01', description: 'Sopros e outros sons cardíacos' },
  { code: 'R04', description: 'Hemorragia das vias respiratórias' },
  { code: 'R05', description: 'Tosse' },
  { code: 'R06', description: 'Anormalidades da respiração' },
  { code: 'R06.0', description: 'Dispneia' },
  { code: 'R06.2', description: 'Sibilo (chiado no peito)' },
  { code: 'R07', description: 'Dor de garganta e no peito' },
  { code: 'R07.0', description: 'Dor de garganta' },
  { code: 'R07.4', description: 'Dor torácica não especificada' },
  { code: 'R09', description: 'Outros sintomas e sinais relativos aos sistemas circulatório e respiratório' },
  { code: 'R10', description: 'Dor abdominal e pélvica' },
  { code: 'R10.0', description: 'Abdômen agudo' },
  { code: 'R10.4', description: 'Outras dores abdominais e as não especificadas' },
  { code: 'R11', description: 'Náusea e vômitos' },
  { code: 'R12', description: 'Pirose (azia)' },
  { code: 'R13', description: 'Disfagia' },
  { code: 'R14', description: 'Flatulência e afecções correlatas' },
  { code: 'R17', description: 'Icterícia não especificada' },
  { code: 'R19', description: 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdômen' },
  { code: 'R20', description: 'Anormalidades da sensação cutânea' },
  { code: 'R21', description: 'Eritema e outras erupções cutâneas não especificadas' },
  { code: 'R22', description: 'Tumefação, massa e caroço localizados na pele e no tecido subcutâneo' },
  { code: 'R25', description: 'Movimentos involuntários anormais' },
  { code: 'R26', description: 'Anormalidades da marcha e da mobilidade' },
  { code: 'R27', description: 'Outras dificuldades de coordenação (ataxia)' },
  { code: 'R29', description: 'Outros sintomas e sinais relativos ao sistema nervoso e ao sistema musculoesquelético' },
  { code: 'R30', description: 'Dor associada à micção' },
  { code: 'R31', description: 'Hematúria não especificada' },
  { code: 'R32', description: 'Incontinência urinária não especificada' },
  { code: 'R33', description: 'Retenção urinária' },
  { code: 'R35', description: 'Poliúria' },
  { code: 'R39', description: 'Outros sintomas e sinais relativos ao sistema urinário' },
  { code: 'R41', description: 'Outros sintomas e sinais relativos às funções cognitivas e à consciência' },
  { code: 'R42', description: 'Tontura e instabilidade (vertigem)' },
  { code: 'R43', description: 'Transtornos do olfato e do paladar' },
  { code: 'R44', description: 'Outros sintomas e sinais relativos às sensações e percepções gerais' },
  { code: 'R45', description: 'Sintomas e sinais relativos ao estado emocional' },
  { code: 'R50', description: 'Febre de origem desconhecida' },
  { code: 'R51', description: 'Cefaleia' },
  { code: 'R52', description: 'Dor não classificada em outra parte' },
  { code: 'R53', description: 'Mal-estar e fadiga' },
  { code: 'R54', description: 'Senilidade' },
  { code: 'R55', description: 'Síncope e colapso' },
  { code: 'R56', description: 'Convulsões não classificadas em outra parte' },
  { code: 'R57', description: 'Choque não classificado em outra parte' },
  { code: 'R58', description: 'Hemorragia não classificada em outra parte' },
  { code: 'R59', description: 'Gânglios linfáticos aumentados de volume' },
  { code: 'R60', description: 'Edema não classificado em outra parte' },
  { code: 'R62', description: 'Ausência de desenvolvimento fisiológico normal esperado' },
  { code: 'R63', description: 'Sintomas e sinais relativos à ingestão de alimentos e de líquidos' },
  { code: 'R63.0', description: 'Anorexia' },
  { code: 'R63.1', description: 'Polidipsia' },
  { code: 'R63.3', description: 'Dificuldade para se alimentar e administração incorreta de alimentos' },
  { code: 'R63.4', description: 'Perda de peso anormal' },
  { code: 'R63.5', description: 'Ganho de peso anormal' },
  { code: 'R64', description: 'Caquexia' },
  { code: 'R65', description: 'Síndrome de resposta inflamatória sistêmica (SIRS)' },
  { code: 'R68', description: 'Outros sintomas e sinais gerais' },
  { code: 'R73', description: 'Glicemia elevada' },
  { code: 'R73.0', description: 'Alteração do teste de tolerância à glicose (pré-diabetes)' },
  { code: 'R79', description: 'Outros achados anormais nos exames laboratoriais do sangue' },
  // ── S: Lesões traumáticas ────────────────────────────────────────────────
  { code: 'S00', description: 'Traumatismo superficial da cabeça' },
  { code: 'S01', description: 'Ferimento da cabeça' },
  { code: 'S02', description: 'Fratura do crânio e dos ossos da face' },
  { code: 'S06', description: 'Traumatismo intracraniano' },
  { code: 'S09', description: 'Outros traumatismos e os não especificados da cabeça' },
  { code: 'S10', description: 'Traumatismo superficial do pescoço' },
  { code: 'S13', description: 'Luxação, entorse e distensão das articulações e dos ligamentos do pescoço' },
  { code: 'S20', description: 'Traumatismo superficial do tórax' },
  { code: 'S22', description: 'Fratura de costela, esterno e coluna torácica' },
  { code: 'S30', description: 'Traumatismo superficial do abdômen, do dorso e da pelve' },
  { code: 'S32', description: 'Fratura da coluna lombar e da pelve' },
  { code: 'S40', description: 'Traumatismo superficial do ombro e do braço' },
  { code: 'S42', description: 'Fratura do ombro e do braço' },
  { code: 'S49', description: 'Outros traumatismos e os não especificados do ombro e do braço' },
  { code: 'S50', description: 'Traumatismo superficial do antebraço e do cotovelo' },
  { code: 'S52', description: 'Fratura do antebraço' },
  { code: 'S60', description: 'Traumatismo superficial do punho e da mão' },
  { code: 'S62', description: 'Fratura ao nível do punho e da mão' },
  { code: 'S70', description: 'Traumatismo superficial do quadril e da coxa' },
  { code: 'S72', description: 'Fratura do fêmur' },
  { code: 'S80', description: 'Traumatismo superficial da perna e do joelho' },
  { code: 'S82', description: 'Fratura da perna inclusive do tornozelo' },
  { code: 'S83', description: 'Luxação, entorse e distensão das articulações e dos ligamentos do joelho' },
  { code: 'S90', description: 'Traumatismo superficial do tornozelo e do pé' },
  { code: 'S92', description: 'Fratura do pé (exceto tornozelo)' },
  // ── T: Intoxicações e outros ─────────────────────────────────────────────
  { code: 'T07', description: 'Traumatismos múltiplos não especificados' },
  { code: 'T14', description: 'Traumatismo de região não especificada do corpo' },
  { code: 'T36', description: 'Intoxicação por antibióticos sistêmicos' },
  { code: 'T39', description: 'Intoxicação por analgésicos não opioides, antipiréticos e antirreumáticos' },
  { code: 'T40', description: 'Intoxicação por narcóticos e psicodislépticos' },
  { code: 'T51', description: 'Efeito tóxico do álcool' },
  { code: 'T71', description: 'Asfixia' },
  { code: 'T74', description: 'Síndromes de maus-tratos' },
  { code: 'T78', description: 'Efeitos adversos não classificados em outra parte' },
  { code: 'T78.0', description: 'Choque anafilático por alimento' },
  { code: 'T78.1', description: 'Outras reações adversas a alimentos' },
  { code: 'T78.4', description: 'Alergia não especificada' },
  // ── U: COVID-19 e outros ─────────────────────────────────────────────────
  { code: 'U07.1', description: 'COVID-19, vírus identificado' },
  { code: 'U07.2', description: 'COVID-19, vírus não identificado' },
  { code: 'U09', description: 'Afecção pós-COVID-19' },
  // ── Z: Fatores que influenciam o estado de saúde ─────────────────────────
  { code: 'Z00', description: 'Exame geral e investigação de pessoas sem queixa' },
  { code: 'Z01', description: 'Outros exames e investigações em pessoas sem queixa' },
  { code: 'Z02', description: 'Exame e encontro para fins administrativos' },
  { code: 'Z03', description: 'Exame médico e observação por suspeita de doenças e afecções descartadas' },
  { code: 'Z04', description: 'Exame e observação por outras razões' },
  { code: 'Z08', description: 'Exame de acompanhamento após tratamento por neoplasia maligna' },
  { code: 'Z09', description: 'Exame de acompanhamento após tratamento de outras afecções além de neoplasia maligna' },
  { code: 'Z11', description: 'Exame especial de rastreamento de doenças infecciosas e parasitárias' },
  { code: 'Z12', description: 'Exame especial de rastreamento de neoplasias' },
  { code: 'Z13', description: 'Exame especial de rastreamento de outras doenças e transtornos' },
  { code: 'Z20', description: 'Contato com e exposição a doenças transmissíveis' },
  { code: 'Z21', description: 'Estado de infecção assintomática pelo HIV' },
  { code: 'Z23', description: 'Necessidade de vacinação contra doenças bacterianas únicas' },
  { code: 'Z25', description: 'Necessidade de vacinação contra outras doenças virais únicas' },
  { code: 'Z30', description: 'Contracepção (planejamento familiar)' },
  { code: 'Z34', description: 'Supervisão de gravidez normal' },
  { code: 'Z36', description: 'Rastreamento pré-natal' },
  { code: 'Z38', description: 'Nascidos vivos segundo o local de nascimento' },
  { code: 'Z39', description: 'Exame e assistência pós-parto' },
  { code: 'Z41', description: 'Procedimentos para outros fins que não o de remediar o estado de saúde' },
  { code: 'Z46', description: 'Adaptação e manuseio de outros aparelhos' },
  { code: 'Z47', description: 'Outros cuidados pós-procedimento ortopédico' },
  { code: 'Z48', description: 'Outros cuidados pós-procedimento cirúrgico' },
  { code: 'Z50', description: 'Assistência envolvendo o uso de procedimentos de reabilitação' },
  { code: 'Z51', description: 'Outro tratamento médico' },
  { code: 'Z51.1', description: 'Sessão de quimioterapia' },
  { code: 'Z51.2', description: 'Sessão de radioterapia' },
  { code: 'Z57', description: 'Exposição a fatores de risco ocupacionais' },
  { code: 'Z60', description: 'Problemas relacionados com o meio social' },
  { code: 'Z63', description: 'Outros problemas relacionados com o grupo primário de apoio' },
  { code: 'Z71', description: 'Pessoas em contato com os serviços de saúde para aconselhamento' },
  { code: 'Z72', description: 'Problemas relacionados com o estilo de vida' },
  { code: 'Z73', description: 'Problemas relacionados com a organização do modo de vida' },
  { code: 'Z74', description: 'Problemas relacionados com a dependência de cuidados prestados por outra pessoa' },
  { code: 'Z75', description: 'Problemas relacionados com instalações médicas e outros cuidados de saúde' },
  { code: 'Z76', description: 'Pessoas em contato com os serviços de saúde em outras circunstâncias' },
  { code: 'Z82', description: 'História familiar de certas incapacidades e doenças crônicas' },
  { code: 'Z85', description: 'História pessoal de neoplasia maligna' },
  { code: 'Z87', description: 'História pessoal de outras doenças e afecções' },
  { code: 'Z88', description: 'História pessoal de alergia a drogas, medicamentos e substâncias biológicas' },
  { code: 'Z96', description: 'Presença de outros implantes funcionais' },
  { code: 'Z98', description: 'Outros estados pós-cirúrgicos' },
];
