project_id = "fwyulywxhjyxdreeuqna"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.mercadopago-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.redeem-patient-chart]
    verify_jwt = false
  [functions.seed-qa-users]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.validate-clinic-code]
    verify_jwt = false
